apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: strimzi-operator
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://strimzi.io/charts/            # or the repoURL you added to argocd
    chart: strimzi-kafka-operator
    targetRevision: 0.41.0                         # pick a chart version
    helm:
      releaseName: strimzi
      values: |
        watchNamespaces: ["kafka"]
  destination:
    server: https://kubernetes.default.svc
    namespace: kafka
  syncPolicy:
    automated:
      prune: true
      selfHeal: true