apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: my-cluster-kafka
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/cabernal4/strimzy-poc
    path: apps/kafka-clusters         # Path where Kafka-single-node.yaml lives
    targetRevision: main
  destination:
    server: https://kubernetes.default.svc
    namespace: kafka                  # Must match Kafka CRs
  syncPolicy:
    automated:
      prune: true
      selfHeal: true